### ISSUE TITLE
Could not find a test logger with URI or FriendlyName 'xunit'.

### ISSUE THREAD

**Issue by nulltoken** [Faizan2304/LoggerExtensions#10]
Hello,

Just updated to latest version (1.1.0-post-rtm) and now running tests fails with the following error message `Could not find a test logger with URI or FriendlyName 'xunit'.`

Repro steps:
- Create a new project from VS2017 (.NET Core/Xunit Test project)
- Reference NuGet package XunitXml.TestLogger 1.1.0-post-rtm
- Update the created `UnitTest1.cs` file with `Assert.Equal(1, 1);` as the body of the `Test1` method
- run `dotnet test` from powershell -> PASS

```
PS C:\Users\em\Documents\Visual Studio 2017\Projects\XUnitTestProject1\XUnitTestProject1> dotnet test
Build started, please wait...
Build completed.

Test run for C:\Users\em\Documents\Visual Studio 2017\Projects\XUnitTestProject1\XUnitTestProject1\bin\Debug\netcoreapp1.1\XUnitTestProject1.dll(.NETCoreApp,Version=v1.1)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.5101041]   Discovering: XUnitTestProject1
[xUnit.net 00:00:00.6061954]   Discovered:  XUnitTestProject1
[xUnit.net 00:00:00.6485400]   Starting:    XUnitTestProject1
[xUnit.net 00:00:00.7669133]   Finished:    XUnitTestProject1

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.3922 Seconds
```

- run `dotnet test  --test-adapter-path:. --logger:xunit` from powershell -> FAIL

```
PS C:\Users\em\Documents\Visual Studio 2017\Projects\XUnitTestProject1\XUnitTestProject1> dotnet test  --test-adapter-path:. --logger:xunit
Build started, please wait...
Build completed.

Test run for C:\Users\em\Documents\Visual Studio 2017\Projects\XUnitTestProject1\XUnitTestProject1\bin\Debug\netcoreapp1.1\XUnitTestProject1.dll(.NETCoreApp,Version=v1.1)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Could not find a test logger with URI or FriendlyName 'xunit'.
```

**Comment by codito** [comment]
@nulltoken I think the dotnet-cli version in this case is RTM version (15.0.x). The post-rtm nuget requires dotnet-cli shipped with VS 2017 Update 1 onwards; this is because of a change in the test platform.

**Comment by nulltoken** [comment]
@codito Thanks for the feedback.

Below the dotnet sdk version

```ps
PS C:\Users\em\Documents\Visual Studio 2017\Projects\XUnitTestProject1\XUnitTestProject1> dotnet --info
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```
Looks like I'm running sdk `1.0.4` which is the latest **[stable](https://github.com/dotnet/cli/releases)** release, as far as I know.

Which version should I be using?

**Comment by nulltoken** [comment]
@Faizan2304 Any thought?

**Comment by Bala2Excel** [comment]
HI,
I am also facing the same issue. Can you please suggest?

**Comment by Faizan2304** [comment]
@nulltoken  @Bala2Excel 

```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```
this package doesn't have testplatform which can handle package  `XunitXml.TestLogger` (`1.1.0-post-rtm` ). You guys have to use `XunitXml.TestLogger` (`1.0.3-pre-rtm`) to make it work.

If you have dotnet installed of version (https://github.com/dotnet/cli/releases/tag/v2.0.0-preview2) then you have to use `XunitXml.TestLogger` (`1.1.0-post-rtm` )

I hope this will solve your issue.

**Comment by nulltoken** [comment]
@Faizan2304 Thanks. As this requirement isn't very easy to figure out, maybe adding a `CHANGELOG.md` in the repo describing the changes and the requirements for each release may help other users.

**Comment by Faizan2304** [comment]
> @Faizan2304 Thanks. As this requirement isn't very easy to figure out, maybe adding a CHANGELOG.md in the repo describing the changes and the requirements for each release may help other users.

@nulltoken Thanks for suggestion. I will add CHANGE.md.

**Comment by ilatypov** [comment]
In my case, I figured I never built the test project and my running `dotnet test --no-build ...` missed the XUnit test logger package.

**Comment by tejakrishnam** [comment]
@Faizan2304 , I am using Azure Devops for the build pipeline.
I am doing a dotnet test --logger:"xunit;LogFilePath=test_result.xml" and used 
<PackageReference Include="XunitXml.TestLogger" Version="1.0.3-pre-rtm" />
in one of the test csproj  file and restored the entire solution and then tried to do a dotnet test again with the logger enabled for xunit as above, I am still facing the same issue.
Could you please help me in moving ahead towards the fix.

**Comment by codito** [comment]
@tejakrishnam we have extract the xunit logger into separate package (this issue is several years old). Please take a look at this instructions: https://github.com/spekt/xunit.testlogger#usage. Use the latest version of xunit logger mentioned there. If you're still facing an error, kindly open an issue here: https://github.com/spekt/xunit.testlogger/issues

**Comment by shashank21j** [comment]
Adding <PackageReference Include="XunitXml.TestLogger" Version="2.1.26" /> to csproj file worked for me.
