### ISSUE TITLE
Issue with case sensitivity of filenames on Linux

### ISSUE THREAD

**Issue by Sharparam** [Faizan2304/LoggerExtensions#16]
When using the `NUnitXML.TestLogger` package on a Linux system, there is an issue with a mismatch of casing between the properties file and the actual DLL file.

The properties file references

    Microsoft.VisualStudio.TestPlatform.Extension.NUnit.Xml.TestAdapter.dll

But the actual file name is

    Microsoft.VisualStudio.TestPlatform.Extension.Nunit.Xml.TestAdapter.dll

(Notice the difference in casing in the word "Nunit".)

This issue can be observed in the following TravisCI build: https://travis-ci.org/CoraleStudios/Colore/jobs/297388218

(Notice how it builds fine in the macOS setting, which has a case insensitive file system.)

It seems this issue might stem from the `build.ps1` file here:
https://github.com/Faizan2304/LoggerExtensions/blob/master/scripts/build.ps1#L169-L173

After adding a bit of code to the build script to rename the files with the proper `NUnit` name (notice the capital U), [the build was successful](https://travis-ci.org/CoraleStudios/Colore/jobs/297409765).

**Comment by TheSatoshiChiba** [comment]
Is there actually a fix planned? I am using the current NUnit Logger package from NuGet and I am running into this exact same issue. Windows and OSX work fine. Linux is bust :(

**Comment by codito** [comment]
@TheSatoshiChiba looking into this. Should have a fixed package out in next few days.

**Comment by TheSatoshiChiba** [comment]
That would be great. Thank you.
