### ISSUE TITLE
xunit logger doesn't work on linux

### ISSUE THREAD

**Issue by rohit21agrawal** [Faizan2304/LoggerExtensions#18]
Running ``` dotnet vstest ``` on netcoreapp1.0 test libraries on ubuntu 16.04 with CLI downloaded from the link : https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.4/dotnet-dev-ubuntu.16.04-x64.1.0.4.tar.gz 

Version of xunit logger : 1.0.3-pre-rtm

I get the following error:

```
2018-01-08T05:45:49.3758556Z   The path '.' specified in the 'TestAdapterPath' does not contain any test adapters, provide a valid path and try again.
2018-01-08T05:45:49.3786919Z   
2018-01-08T05:45:49.4155345Z   Could not find a test logger with URI or FriendlyName 'xunit'.
```

**Comment by rohit21agrawal** [comment]
i see similar results on mac too

**Comment by Faizan2304** [comment]
Can you please try latest version 2.0.0 (https://www.nuget.org/packages/XunitXml.TestLogger/2.0.0).

**Comment by rohit21agrawal** [comment]
my bad, turns out with Linux/Mac, the path is evaluated a little differently and I had to pass the full path to the directory which contained the logger and test adapter.
