### ISSUE TITLE
--test-adapter-path: required for .NET core, but not full framework

### ISSUE THREAD

**Issue by optical** [Faizan2304/LoggerExtensions#2]
I suspect this is the wrong place for this issue, but never the less perhaps you might have some idea on the issue,

Why is it that when you run `dotnet test --logger:xunit` under .NET core you need to specify `--test-adapter-path:.`, whereas under a .NET framework project you are able to omit this argument? The behaviour is pretty confusing and took me a reasonable amount of time to realise my error.

**Comment by codito** [comment]
@optical we're fixing this in next update to `dotnet test` (https://github.com/Microsoft/vstest/issues/616, https://github.com/Microsoft/vstest/issues/557).

**Comment by optical** [comment]
Aha, excellent. Thanks for that. What will the typical acquisition story be for that fix? My guess is it'll go out in a release of the dotnet sdk? If so, how would one figure out which version the fix will be contained in?

**Comment by Faizan2304** [comment]
@optical  apology for responding so late. We have fixed it with [TestPlatform release](https://github.com/Microsoft/vstest/releases/tag/v15.3.0-preview-20170425-07 )
I don't know the exact version of dotnet sdk which has this fix but the later version will sure have this.

**Comment by optical** [comment]
Thanks for the follow up. Will check it out.
