### ISSUE TITLE
NUnitLogger - StdOut is not being captured

### ISSUE THREAD

**Issue by ztittle** [Faizan2304/LoggerExtensions#21]
I'm seeing that test output is never written to the log. After some investigation, it looks like the code below creates a StringBuilder, but it never writes it to an xml message element.

https://github.com/Faizan2304/LoggerExtensions/blob/f353ba30ffc8a57a0b1d791e2d277148ec4ae4ee/src/NUnit.Xml.TestLogger/NUnitXmlTestLogger.cs#L389

The XUnit logger does not have this issue because it correctly outputs to output element https://github.com/Faizan2304/LoggerExtensions/blob/master/src/Xunit.Xml.TestLogger/XunitXmlTestLogger.cs#L455

**Comment by codito** [comment]
@ztittle thanks for reporting this issue! From the [nunit xml spec](https://github.com/nunit/docs/wiki/Test-Result-XML-Format#output), it looks like we should capture stdout in `<output>` element. Would you like to share a patch to fix this issue?

**Comment by ztittle** [comment]
See https://github.com/Faizan2304/LoggerExtensions/pull/22

**Comment by codito** [comment]
Thank you so much!
