### ISSUE TITLE
Example usage doesn't work as described

### ISSUE THREAD

**Issue by deppe** [Faizan2304/LoggerExtensions#3]
Based on example in README.md, I'm running

```
dotnet test --test-adapter-path:. --logger:xunit;LogFilePath=results.xml
```

This creates a results file as "TestResults/TestResults.xml" instead of `results.xml` in the current directory.

Compare this with

```
dotnet test --test-adapter-path:. --logger "xunit;LogFilePath=results.xml"
```

Which creates `results.xml` in the current directory as expected. This is run using version 1.0.2-pre-rtm

**Comment by Faizan2304** [comment]
Hi @deppe. thank you for opening this issue.
 I tried locally to repro it but unfortunately no luck.
For me both command
` dotnet test --test-adapter-path:. --logger:xunit;LogFilePath=results.xml` and
`dotnet test --test-adapter-path:. --logger "xunit;LogFilePath=results.xml"` creating `result.xml` in the current directory.

I m closing this now, please reopen it if you have any concern of query.
