### ISSUE TITLE
could not find a test logger with uri or friendlyname Appveyor

### ISSUE THREAD

**Issue by holmescn** [Faizan2304/LoggerExtensions#4]
I am using VS2017 and dotnet 1.1 to write a ASP.NET Core Web app. There are two (actually three) projects: one is the main project, the other is the unit test project which uses vstest to do the unit testing.

I followed the README to add the package and run with `dotnet test --test-adapter-path:. --logger:Appveyor`, but got the error said:

    could not find a test logger with uri or friendlyname Appveyor

Does the adapter not support the latest dotnet runtime? Or what I am missing?

**Comment by Faizan2304** [comment]
@holmescn : What is the version of visual studio you are using?

**Comment by holmescn** [comment]
@Faizan2304 I have forgot the version. Several months passed, perhaps the problem already solved. I haven't tested it yet.

**Comment by Faizan2304** [comment]
Use this package of [Appveyor logger](https://www.nuget.org/packages/Appveyor.TestLogger/1.1.0-post-rtm) if issue persist.
