### ISSUE TITLE
XUnit test XML output invalid on linux

### ISSUE THREAD

**Issue by green-mdoerflinger** [Faizan2304/LoggerExtensions#5]
When using the XunitXml.TestLogger on linux to run 

```
dotnet test --test-adapter-path . --logger xunit;LogFilePath=testResults.xml
```

the created XML is invalid. It contains an additional `s>` at the very end after the closing `</assemblies>` tag. 

```
<?xml version="1.0" encoding="utf-8"?>
<assemblies timestamp="05/22/2017 09:14:07">
  <assembly name="/home/administrator/jenkins/workspace/project_github/project/test/project.Tests/bin/Debug/netcoreapp1.0/project.Tests.dll" run-date="2017-05-22" run-time="09:14:07" total="45" passed="45" failed="0" skipped="0" time="6.967" errors="0">
    <errors />
...
  </assembly>
</assemblies>s>
```

I am using Dotnet Core SDK 1.0.4 on Ubuntu 14.04.5 LTS to run the tests. On OSX 10.12 it works fine (also using Dotnet Core SDK 1.0.4).

**Comment by Faizan2304** [comment]
@green-mdoerflinger : Thank you for reporting this issue.
This has been fixed with https://github.com/Faizan2304/LoggerExtensions/pull/6
I will publish new bits on nuget soon and will let you know.

**Comment by Faizan2304** [comment]
[This package](https://www.nuget.org/packages/XunitXml.TestLogger/1.0.3-pre-rtm) has the fix.
